variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

stages:
  - template: .azure-pipelines/test-tf-provider-modules.yml
    parameters:
      environment: test
      providerName: aws
      providerServiceConnection: sje-aws-origin
      cloudRegion: us-east-1
      runIdentifier: tf-run-aws-test-stuartellis-origin-us-east-1-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/aws
      vmImage: ${{ variables.vmImage }}
      terraformModules:
        sns_topic: sns_topic
