parameters:
  - name: terraformModules
    displayName: Terraform modules
    type: object
    default:
      custom_ssm_parameters: custom_ssm_parameters
      sns_topic: sns_topic

variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

resources:
  repositories:
    - repository: shared
      type: git
      name: azdo-shared-tasks
      ref: refs/heads/main

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md

stages:
  - template: pipeline-templates/terraform/test-tf-modules.yml@shared
    parameters:
      environment: infra-test
      providerName: aws
      providerServiceConnection: sje-aws-origin
      cloudRegion: us-east-1
      runIdentifier: tf-run-aws-test-stuartellis-origin-us-east-1-$(Build.BuildId)
      terraformInstallationDir: $(Agent.TempDirectory)
      terraformSourcePath: $(Build.Repository.LocalPath)/stuartellis-org-tf-modules/aws
      vmImage: ${{ variables.vmImage }}
      terraformModules: ${{ parameters.terraformModules }}
