parameters:
  - name: dryRun
    displayName: Dry run only
    type: boolean
    default: true
  - name: terraformModules
    displayName: Terraform modules
    type: object
    default:
      shared_ssm_parameters: shared_ssm_parameters
      sns_topic: sns_topic

variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

stages:
  - template: .azure-pipelines/test-tf-modules.yml
    parameters:
      environment: infra-test
      providerName: aws
      providerServiceConnection: sje-aws-origin
      cloudRegion: us-east-1
      runIdentifier: tf-run-aws-test-stuartellis-origin-us-east-1-$(Build.BuildId)
      terraformSourcePath: $(Build.Repository.LocalPath)/aws
      vmImage: ${{ variables.vmImage }}
      terraformModules: ${{ parameters.terraformModules }}
