parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: targetName
    type: string
  - name: cmdExe
    type: string
  - name: cmdOptions
    type: string
  - name: workingDirectory
    type: string

steps:
  - task: AWSShellScript@1
    displayName: Run TFLint for ${{ parameters.targetName }}
    inputs:
      awsCredentials: ${{ parameters.providerServiceConnection }}
      regionName: ${{ parameters.cloudRegion }}
      scriptType: inline
      inlineScript: |
        ${{ parameters.cmdExe }} ${{ parameters.cmdOptions }}
      disableAutoCwd: true
      workingDirectory: ${{ parameters.workingDirectory }}
