parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: environment
    type: string
  - name: providerName
    type: string
  - name: runIdentifier
    type: string
  - name: terraformSourcePath
    type: string
  - name: terraformModules
    type: object
  - name: vmImage
    type: string

stages:
  - stage:
    displayName: Terraform for ${{ parameters.providerName }}
    jobs:
      - deployment:
        displayName: Test with ${{ parameters.environment }} ${{ parameters.cloudRegion }} with ${{ parameters.providerServiceConnection }}
        pool:
          vmImage: ${{ parameters.vmImage }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - template: setup-binaries.yml
                  parameters:
                    workingDirectory: $(Build.Repository.LocalPath)

                - ${{ each terraformModule in parameters.terraformModules }}:
                    - template: create-output-dir.yml
                      parameters:
                        sourceDir: $(Build.Repository.LocalPath)
                        outputDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}/${{ terraformModule.Key }}

                    - template: test-tf-code.yml
                      parameters:
                        cloudRegion: ${{ parameters.cloudRegion }}
                        providerName: ${{ parameters.providerName }}
                        providerServiceConnection: ${{ parameters.providerServiceConnection }}
                        runIdentifier: tf-testing-${{ parameters.providerName }}-${{ parameters.environment }}-${{ parameters.providerServiceConnection }}-modules-${{ parameters.cloudRegion }}-${{ parameters.terraformModule.Key }}-$(Build.BuildId)
                        targetName: ${{ terraformModule.Key }}
                        terraformOutputDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}/${{ terraformModule.Key }}
                        terraformSourceDir: ${{ parameters.terraformSourcePath }}/${{ terraformModule.Key }}
                        terraformExe: terraform
                        tflintExe: $(Build.Repository.LocalPath)/bin/tflint

                - template: archive-outputs.yml
                  parameters:
                    archiveName: ${{ parameters.runIdentifier }}
                    rootDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}
