parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: providerName
    type: string
  - name: runIdentifier
    type: string
  - name: targetName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceDir
    type: string
  - name: terraformExe
    type: string
  - name: tflintExe
    type: string

steps:
  - template: run-tf-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      cmdName: init
      cmdExe: ${{ parameters.terraformExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}

  - template: run-tf-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      cmdName: validate
      cmdExe: ${{ parameters.terraformExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}

  - template: run-tf-lint-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      cmdExe: ${{ parameters.tflintExe }}
      cmdOptions: --init -c ${{ parameters.terraformSourceDir }}/../.tflint.hcl
      workingDirectory: ${{ parameters.terraformSourceDir }}

  - template: run-tf-lint-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      cmdExe: ${{ parameters.tflintExe }}
      cmdOptions: -c ${{ parameters.terraformSourceDir }}/../.tflint.hcl -f junit > ${{ parameters.terraformOutputDir }}/tflint-results.xml
      workingDirectory: ${{ parameters.terraformSourceDir }}

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: Publish linter results for ${{ parameters.targetName }}
    inputs:
      testRunner: JUnit
      testResultsFiles: ${{ parameters.terraformOutputDir }}/tflint-results.xml
      testRunTitle: ${{ parameters.targetName }}-tflint-results
